### ISSUE TITLE
The posteriors results page is does not display anymore

### ISSUE THREAD

**Issue by ogrisel** [sbi-benchmark/streamlit#1]
I tried on firefox and chrome on 2 different machines: 

https://sbi-benchmark.github.io/results/posteriors/

and I get:

Oh no.
Error running app. If this keeps happening, please file an issue.

**Comment by jan-matthis** [comment]
Thanks for reporting this -- the page should be available again now.

Unfortunately this keeps happening from time to time, without apparent reason. The page is hosted externally on Streamlit's servers. Hopefully there will be an automated way of catching these errors in the future: https://discuss.streamlit.io/t/app-crashes-after-some-time-without-error/8927/8

**Comment by pipme** [comment]
It's happening again 🤔

**Comment by jan-matthis** [comment]
Should be fixed now, thanks for reporting!
